In [2]:
import numpy as np

## reshape

배열의 차원을 재구조화, 변경

요소의 개수 같아야 함

In [3]:
# reshape
array = np.arange(1,9)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
array.shape

(8,)

In [5]:
array.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
array.reshape(2,4).shape

(2, 4)

In [7]:
array.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
array.reshape(-1,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## ravel

다차원 배열을 낮은 차원으로 반환 (원본 뷰)

ravel 데이터 수정하면 원본 데이터도 수정

In [9]:
a = np.array([  [[1,2], [3,4]],
                [[1,2], [3,4]]
             ]
            )
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [12]:
b = a.ravel()
print(b)

[1 2 3 4 1 2 3 4]


In [13]:
b[4] = 10
print(b)

[ 1  2  3  4 10  2  3  4]


In [14]:
print(a)

[[[ 1  2]
  [ 3  4]]

 [[10  2]
  [ 3  4]]]
