In [1]:
import numpy as np

In [5]:
# reshape
array = np.arange(1,9)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
array.shape

(8,)

In [7]:
array.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
array.reshape(2,4).shape

(2, 4)

In [9]:
array.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
array.reshape(-1,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])